### PR TITLE
get rid of subarray calls, added testcases

### PR DESCRIPTION
**Pull request by georgi**
changed subarray calls to calls with array offset. added testcase for fasdct, imdct_l, imdct_s

imdct_s had a serious bug. the array indexing wasn accounting the 2dimensional structure of imdct_s.

### CODE REVIEW

**Comment by georgi** [comment]
but still the pcm output sounds like crap :(

**Comment by georgi** [comment]
for the sake of portability we should hide the array construction beneath a function, that decides at runtime, which implementation to be used (js array, typed-array).

**Comment by nddrylliog** [comment]
So, what is next? scalefactors? reorder? freqinver? alias_reduce?
On Jun 2, 2011 4:00 AM, "georgi" <
reply@reply.github.com>
wrote:

**Comment by georgi** [comment]
I'm looking at scalefactors now.

**Pull request merged**
