### PR TITLE
Add the ability to listen to a specific track using the /play/:trackId URL.

### PR DESCRIPTION
**Pull request by romac**
This pull request lets any user link to a specific track within jsmad.org using an URL like:

http://jsmad.org/play/32949

It also adds a little box with the link, ready for them to be copied and pasted into the favorite IM client or on Facebook.

### CODE REVIEW

**Comment by romac** [comment]
Hope you'll also like the song linked above :)

**Comment by nddrylliog** [comment]
it sounds choppy on Android :)

**Comment by romac** [comment]
^.^ Did you just merged that pull request from your smartphone ? Man I love this thing called the Internet, and especially the great folks at GitHub.
Great, now I see rainbows. And unicorns.

**Comment by nddrylliog** [comment]
yeaw man, I merged it on my bed.

also, jsmad sorta runs on Android, wtf!

**Pull request merged**
