### PR TITLE
full synth test and raw pcm output

### PR DESCRIPTION
**Pull request by georgi**
hi, I am pretty sure, that the input to the synth is broken.
I did some comparisons using debug statements and the sbsamples values were totally different.
Anyway I tested full_synth with a set of 4 frames and the delta to libmad is again smaller than 1e-7.
Should I tackle some of the other functions?

### CODE REVIEW

**Comment by nddrylliog** [comment]
Yes, it sounds likely that something between huffdecode and full_synth is
going wrong. I think resquantize is correct now, which leaves us with the
various DCTs I think. And reorder.
On Jun 1, 2011 11:55 PM, "georgi" <
reply@reply.github.com>
wrote:

**Comment by georgi** [comment]
Ok, I'm going to look at fastsdct now.

**Comment by georgi** [comment]
I just discovered, that my subarray implementation is completely wrong. I assumed subarray returns a copy, but it's specified as a shifted view on the same array. Difficult to implement, because of missing operator overloading.

**Comment by nddrylliog** [comment]
Do we actually need it? Can't we just use Float32Array?

Also, for substrate, we can also just add an offset parameter to the
functions that require it.
On Jun 2, 2011 3:01 AM, "georgi" <
reply@reply.github.com>
wrote:

**Comment by georgi** [comment]
What do you mean? Float32Array of v8-typed-arrays?
Am 02.06.2011 03:12 schrieb "nddrylliog" <
reply@reply.github.com>:

**Pull request merged**
